const characters = [
    {
        name:'esi',
        idle:'chars/esi/player.png',
        parry:'chars/esi/player2.png',
        special:'chars/esi/player.png',
        specials:[portal,direct_shot],
        ultimate:super_shot
    },
     {
        name:'sakura',
        idle:'chars/sakura/idle.png',
        parry:'chars/sakura/parry.png',
        special:'chars/sakura/special.png',
        specials:[projectile,direct_shot],
        ultimate:super_shot,
        voice_lines:['chars/sakura/1.wav','chars/sakura/2.wav','chars/sakura/3.wav']
    },
    {
        name:'lilith', 
        idle:'chars/lilith/idle.png',
        parry:'chars/lilith/parry.png',
        special:'chars/lilith/special1.png',
        specials:[echo,shadowclones],
        ultimate:super_shot,
        voice_lines:['chars/lilith/1.wav','chars/lilith/3.wav','chars/lilith/1.wav']
    },
    {
        name:'hsienko',
        idle:'chars/hsienko/idle.png',
        parry:'chars/hsienko/parry.png',
        special:'chars/hsienko/special.png',
        specials:[curve,teleport],
        ultimate:super_shot
    },
    {
        name:'sonson',
        idle:'chars/sonson/idle.png',
        parry:'chars/sonson/parry.png',
        special:'chars/sonson/special.png',
        specials:[feint,happy_chaos],
        ultimate:great_wall,
        voice_lines:['chars/sonson/1.wav','chars/sonson/2.wav','chars/sonson/3.wav']
    },
    {
        name:'urien',
        idle:'chars/urien/idle.png',
        parry:'chars/urien/parry.png',
        special:'chars/urien/special.png',
        specials:[reflector,blackhole],
        ultimate:great_wall,
        voice_lines:['chars/urien/1.wav','chars/urien/2.wav','chars/urien/3.wav']
    },
     {
        name:'miku',
        idle:'chars/miku/idle.png',
        parry:'chars/miku/parry.png',
        special:'chars/miku/special.png',
        specials:[reflector,magnetism],
        ultimate:great_wall
    },
    {
        name:'bad guy',
        idle:'chars/badguy/idle.png',
        parry:'chars/badguy/parry.png',
        special:'chars/badguy/special.png',
        specials:[blackhole,direct_shot,projectile,reflector,shadowclones,teleport,curve,feint,echo,magnetism,portal],
        ultimate:super_shot,
        voice_lines:['chars/badguy/1.wav','chars/badguy/2.wav','chars/badguy/3.wav']
    }
]